---
abstract: 'Get a version number via git and a flow-inspired structure.'
author:
  - 'Cory G Watson <gphat@cpan.org>'
build_requires:
  Test::More: 0
  strict: 0
  warnings: 0
configure_requires:
  ExtUtils::MakeMaker: 6.30
dynamic_config: 0
generated_by: 'Dist::Zilla version 4.300006, CPAN::Meta::Converter version 2.113640'
license: perl
meta-spec:
  url: http://module-build.sourceforge.net/META-spec-v1.4.html
  version: 1.4
name: Dist-Zilla-Plugin-Version-Git-Flowish
requires:
  Dist::Zilla::Role::VersionProvider: 0
  Moose: 0
  perl: v5.10
resources:
  homepage: https://github.com/gphat/dist-zilla-plugin-version-git-flowish
  repository: https://github.com/gphat/dist-zilla-plugin-version-git-flowish.git
version: 0.09
